FROM amazoncorretto:20-alpine3.18-jdk

# 設定ファイル等必要なものをコピー
# COPY ./config/ /etc/postgresql/

# 設定ファイルの権限更新
# RUN chmod 644 /etc/postgresql/

# 初期設定に必要なデータをコピー
# COPY ./initdata/ /docker-entrypoint-initdb.d