version: '3'
services:
  java:
    build: ./server
    container_name: java
    env_file:
      - ./server/server.env
    tty: true
    working_dir: /app
    volumes:
      - type: bind # ホストのディレクトリをマウント
        source: ../demo
        target: /app:cached
    ports:
      - 8080:8080
    depends_on: # 依存するコンテナ指定しそれが起動してから動作するようにする
      - postgres
      - redis
      - minio
      
  postgres:
    build: ./database
    container_name: postgres
    env_file:
      - ./database/db.env
    volumes:
      - ./database/data:/var/lib/postgresql/data #実データの永読化
      - ./database/log:/var/log/postgresql #logの永読化
      - ./database/init:/docker-entrypoint-initdb.d #初期データの登録
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.1
    container_name: redis
    ports:
      - 6379:6379

  minio:
    image: minio/minio:RELEASE.2023-09-07T02-05-02Z
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - ./s3/s3.env
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :900 --console-address :9001"
    volumes:
      - ./s3/data:/export

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    ports:
      - 9200:9200
    env_file:
      - ./elasticsearch/elasticsearch.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
      image: docker.elastic.co/kibana/kibana:8.9.2
      environment:
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ports:
        - 5601:5601
      depends_on:
        - elasticsearch