version: '3'
services:
  java:
    build: ./server
    container_name: java
    env_file:
      - ./server/server.env
    tty: true
    working_dir: /app
    volumes:
      - type: bind # ホストのディレクトリをマウント
        source: ../demo
        target: /app
    ports:
      - 8080:8080
    depends_on: # 依存するコンテナ指定しそれが起動してから動作するようにする
      - postgres
      - redis
      
  postgres:
    build: ./database
    container_name: postgres
    env_file:
      - ./database/db.env
    volumes:
      - ./database/data:/var/lib/postgresql/data #実データの永読化
      - ./database/log:/var/log/postgresql #logの永読化
      - ./database/init:/docker-entrypoint-initdb.d #初期データの登録
    ports:
      - 5432:5432

  redis:
    image: redis:7.2.1
    container_name: redis
    ports:
      - 6379:6379

